dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# command to install dependencies
install:
    - git clone https://github.com/BuysDB/HandleLimiter
    - git clone https://github.com/BuysDB/pysamiterators
    pip install -e ./HandleLimiter  -e ./pysamiterators -e .
# command to run tests
script: pytest
